### ISSUE TITLE
S1 morphed images integration

### ISSUE THREAD

**Issue by UndeadFairy** [gtif-cerulean/gtif-cerulean#17]
Sample results from S1 morphed algorithm were provided by D+N and are stored on our s3 bucket: 

eox-gtif-public/test_data_polartep/S1_morphed/      S1A_EW_GRDM_1SDH_sub_20240704T222630_20240704T0222734_054594_06A535_C277_roi_forecast_6_01_NEXTSIM_mpl_cog.tiff

(numbered 1-6)

We should display for each S1 scene all 6 resulted images and user should be able to easily move along the steps (they are not really timestamped, but rather "development"). 

![image](https://github.com/user-attachments/assets/c2c0750f-774c-495a-8ce0-12b562807771)

**Comment by lubojr** [comment]
Example of style https://github.com/eurodatacube/eodash-assets/blob/main/collections/test_assets/cog_style.json should be configurable and it should work - with a range slider for images 1-6.

**Comment by lubojr** [comment]
```
      "properties": {
        "settlementDistance": {
            "type": "number",
            "minimum": 0,
            "maximum": 5000,
            "format": "range",
            "default": 0
        },
```

**Comment by UndeadFairy** [comment]
2 more examples are uploaded to the bucket in two "folders" corresponding to dates 20240831 and 20240902: 

S1_morphed/20240902/S1A_EW_GRDM_1SDH_sub_20240902T154303_20240902T154303_000000_xxxxxx_27FB_roi_forecast_48_36_NEXTSIM_mpl_cog.tif

time aspect is encoded in the file name: name contains 48_36 which stands for 48 hours of forecast overall, of which this is step 36 (in hours).

This name convention is different to the first example

**Comment by lubojr** [comment]
WIP integration in https://github.com/gtif-cerulean/catalog/tree/d_n_data_demo

Not working yet as expected

**Comment by lubojr** [comment]
Catalog collection has been merged to main. There is a known issue after switching the date and loading prediction with index 5 and more which is tracked separately.
