### ISSUE TITLE
Configure testing catalogs from PRs

### ISSUE THREAD

**Issue by lubojr** [gtif-cerulean/gtif-cerulean#18]

**Comment by lubojr** [comment]
PR Catalogs are configured to be deployed. For example https://github.com/gtif-cerulean/catalog/pull/3#issuecomment-2348375259 This catalog deployment can then be accessed via &catalog=pr-1 query parameter - e.g. https://gtif-cerulean.github.io/eodash-client/uc1dashboard/?catalog=pr-3


PRs of client are deployed as well.

**Comment by lubojr** [comment]
cc @UndeadFairy @santilland

**Comment by santilland** [comment]
Awesome!
